// entities
import Ranking from '../entities/Ranking'
import RankingRow from '../entities/RankingRow'

export default function rankingDao(){

    async function getRankings() {
        return [
            new Ranking('A', [
                new RankingRow(1, 'M. Ubilla', 100),
                new RankingRow(2, 'O. Pérez', 60),
                new RankingRow(3, 'C. Obregón', 35),
                new RankingRow(4, 'M. Pribaz', 35),
                new RankingRow(5, 'M. Marella', 18),
                new RankingRow(6, 'N. Arrieta', 18),
                new RankingRow(7, 'A. Guelfi', 18),
                new RankingRow(8, 'L. Giovanetti', 18)
            ]),
            new Ranking('B', [
                new RankingRow(1, 'F. Nateri', 100),
                new RankingRow(2, 'J. Arias', 60),
                new RankingRow(3, 'D. Cáceres', 35),
                new RankingRow(4, 'N. Arrieta', 35),
                new RankingRow(5, 'A. Ribeiro', 18),
                new RankingRow(6, 'J. Suárez', 18),
                new RankingRow(7, 'O. Maresca', 18),
                new RankingRow(8, 'S. Sánchez', 18),
                new RankingRow(9, 'F. Cadilla', 8),
                new RankingRow(10, 'D. Bordegaray', 8),
                new RankingRow(11, 'M. Midowik', 8),
                new RankingRow(12, 'G. Quirque', 8),
                new RankingRow(13, 'M. Alonso', 8),
                new RankingRow(14, 'R. Gomensoro', 8),
                new RankingRow(15, 'J. I. Ferrari', 8),
                new RankingRow(16, 'M. Serra', 8),
                new RankingRow(17, 'E. Edjen', 2),
                new RankingRow(18, 'R. Labanca', 2),
                new RankingRow(19, 'L. Sanguinetti', 2),
                new RankingRow(20, 'N. Zambrano', 2),
                new RankingRow(21, 'F. Portillo', 2),
                new RankingRow(22, 'M. Méndez', 2),
                new RankingRow(23, 'J. Morales', 2),
                new RankingRow(24, 'M. Cantera', 2),
                new RankingRow(25, 'D. Beloqui', 2),
                new RankingRow(26, 'M. Viola', 2),
                new RankingRow(27, 'W. Zeinal', 2),
                new RankingRow(28, 'M. Lauz', 2),
                new RankingRow(29, 'F. Rodríguez', 2)
            ]),
            new Ranking('C', [
                new RankingRow(1, 'F. Portillo', 100),
                new RankingRow(2, 'J. J. Cetraro', 60),
                new RankingRow(3, 'G. Gianero', 35),
                new RankingRow(4, 'M. Bardesio', 35),
                new RankingRow(5, 'D. Ramos', 18),
                new RankingRow(6, 'A. Rodríguez', 18),
                new RankingRow(7, 'Y. Rajab', 18),
                new RankingRow(8, 'F. Cerda', 18),
                new RankingRow(9, 'J. Suárez', 8),
                new RankingRow(10, 'M. Laguna', 8),
                new RankingRow(11, 'M. Correa', 8),
                new RankingRow(12, 'N. D\'Angelo', 8),
                new RankingRow(13, 'D. Bordegaray', 8),
                new RankingRow(14, 'C. Folle', 8),
                new RankingRow(15, 'J. A. Díaz', 8),
                new RankingRow(16, 'C. Rossi', 8),
                new RankingRow(17, 'V. Crosa', 2),
                new RankingRow(18, 'P. Milburn', 2),
                new RankingRow(19, 'S. Facchín', 2),
                new RankingRow(20, 'J. I. Romero', 2),
                new RankingRow(21, 'M. Cantera', 2),
                new RankingRow(22, 'M. Aguilar', 2),
                new RankingRow(23, 'V. Passanante', 2),
                new RankingRow(24, 'F. Álvarez', 2),
                new RankingRow(25, 'J. Montano', 2),
                new RankingRow(26, 'B. Farías', 2),
                new RankingRow(27, 'F. Márquez', 2),
                new RankingRow(28, 'M. Álvez', 2),
                new RankingRow(29, 'R. Labanca', 2)
            ]),
            new Ranking('D', [
                new RankingRow(1, 'M. Laguna', 100),
                new RankingRow(2, 'J. I. Romero', 60),
                new RankingRow(3, 'B. Farías', 35),
                new RankingRow(4, 'I. Ponce', 35),
                new RankingRow(5, 'S. Facchín', 18),
                new RankingRow(6, 'A. Montaner', 18),
                new RankingRow(7, 'V. Passanante', 18),
                new RankingRow(8, 'P. Medrano', 18),
                new RankingRow(9, 'G. Mesorio', 8),
                new RankingRow(10, 'A. Abella', 8),
                new RankingRow(11, 'J. Calvo', 8),
                new RankingRow(12, 'L. Moreno', 8),
                new RankingRow(13, 'M. Richly', 8),
                new RankingRow(14, 'A. Da Silva', 8),
                new RankingRow(15, 'M. Bardesio', 8),
                new RankingRow(16, 'M. Moreira', 8),
                new RankingRow(17, 'D. Behar', 2),
                new RankingRow(18, 'J. Montano', 2),
                new RankingRow(19, 'D. Sieradski', 2),
                new RankingRow(20, 'A. Piccolo', 2),
                new RankingRow(21, 'F. Scalone', 2),
                new RankingRow(22, 'M. Aguilar', 2),
                new RankingRow(23, 'C. Grandjean', 2),
                new RankingRow(24, 'J. Rosales', 2),
                new RankingRow(25, 'M. Patrone', 2),
                new RankingRow(26, 'J. A. Díaz', 2),
                new RankingRow(27, 'F. Facchín', 2),
                new RankingRow(28, 'F. Cerda', 2),
                new RankingRow(29, 'R. Flores', 2),
                new RankingRow(30, 'S. Maidana', 2),
                new RankingRow(31, 'A. Alori', 2)
            ]),
            new Ranking('E', [
                new RankingRow(1, 'M. Patrone', 100),
                new RankingRow(2, 'J. M. Presno', 60),
                new RankingRow(3, 'I. Ponce', 35),
                new RankingRow(4, 'G. Bastón', 35),
                new RankingRow(5, 'A. Da Silva', 18),
                new RankingRow(6, 'F. Gómez', 18),
                new RankingRow(7, 'F. Bouza', 18),
                new RankingRow(8, 'A. Abella', 18),
                new RankingRow(9, 'J. P. Melián', 8),
                new RankingRow(10, 'M. Pereira', 8),
                new RankingRow(11, 'I. Obregón', 8),
                new RankingRow(12, 'M. Moreira', 8),
                new RankingRow(13, 'D. Signorelli', 8),
                new RankingRow(14, 'F. Facchín', 8),
                new RankingRow(15, 'M. Ceretta', 8),
                new RankingRow(16, 'C. Grandjean', 8),
                new RankingRow(17, 'C. Martínez', 2),
                new RankingRow(18, 'M. Solari', 2),
                new RankingRow(19, 'R. Flores', 2),
                new RankingRow(20, 'E. Lanaro', 2),
                new RankingRow(21, 'F. Perdomo', 2),
                new RankingRow(22, 'H. Voituret', 2),
                new RankingRow(23, 'D. Behar', 2),
                new RankingRow(24, 'C. Pernas', 2),
                new RankingRow(25, 'T. Rosas', 2),
                new RankingRow(26, 'G. Hormaeche', 2),
                new RankingRow(27, 'G. Arias', 2),
                new RankingRow(28, 'M. Casamayou', 2),
                new RankingRow(29, 'F. Scalone', 2)
            ])
        ]
    }


    
    return Object.freeze({ 
        getRankings
    });
}